/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Image_steganography;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.SecretKey;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author locnqt
 */
public class GUI extends javax.swing.JFrame {

    private static String sourceFilePath = "";
    private static String destFilePath = "";
    private static String fileName = "";
    private Ste s = new Ste();
    private AES aes = new AES();
    private myAES myaes = new myAES();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setResizable(false);
        setTitle("Image Steganography");
        setLocationRelativeTo(null);
        TX_input_img.setEditable(false);
        TX_input_mess.setEditable(false);
        TX_output_img.setEditable(false);
        TX_decryp_img.setEditable(false);
//        TX_input_key.setEditable(false);
        TX_decryp_key.setMaximumSize(new Dimension(210,20));

    }

    public static BufferedImage resize(BufferedImage image, int width, int height) {
        BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(image, 0, 0, width, height, null);
        g2d.dispose();
        return bi;
    }

//    private void showMessage(String message, String title) {
//        JOptionPane.showMessageDialog(this, message, title, JOptionPane.INFORMATION_MESSAGE);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Btn_input_img = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        TX_input_mess = new javax.swing.JTextField();
        Btn_input_mess = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXA_input_mess = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TX_input_key = new javax.swing.JTextField();
        TX_input_img = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        LB_origin_img1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LB_enc_img1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LB_origin_img_size1 = new javax.swing.JLabel();
        LB_enc_img_size1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LB_notify1 = new javax.swing.JLabel();
        Btn_exit1 = new javax.swing.JButton();
        Btn_clear1 = new javax.swing.JButton();
        Btn_enc = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        TX_output_img = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        TX_decryp_img = new javax.swing.JTextField();
        Btn_decryp_img = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXA_decryp_mess = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        TX_decryp_key = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        LB_notify2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        LB_enc_img2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        LB_enc_img_size2 = new javax.swing.JLabel();
        Btn_exit2 = new javax.swing.JButton();
        Btn_decryp = new javax.swing.JButton();
        Btn_clear2 = new javax.swing.JButton();
        Btb_save_mess = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Btn_exit3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText("Choose Image: ");

        Btn_input_img.setText("Browse");
        Btn_input_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_input_imgActionPerformed(evt);
            }
        });

        jLabel11.setText("Choose message: ");

        Btn_input_mess.setText("Browse");
        Btn_input_mess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_input_messActionPerformed(evt);
            }
        });

        TXA_input_mess.setColumns(20);
        TXA_input_mess.setRows(5);
        jScrollPane1.setViewportView(TXA_input_mess);

        jLabel12.setText("Message: ");

        jLabel13.setText("Key : ");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Image Detail"));

        LB_origin_img1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setText("Original image");

        LB_enc_img1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setText("Encrypted image");

        LB_origin_img_size1.setText("Size: ");

        LB_enc_img_size1.setText("Size: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_enc_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LB_origin_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel16)
                        .addGap(81, 81, 81)
                        .addComponent(LB_origin_img_size1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel18)
                        .addGap(65, 65, 65)
                        .addComponent(LB_enc_img_size1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_origin_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(LB_origin_img_size1))
                .addGap(10, 10, 10)
                .addComponent(LB_enc_img1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(LB_enc_img_size1))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("NOTIFICATION"));

        LB_notify1.setText("notify");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_notify1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_notify1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Btn_exit1.setText("Exit");
        Btn_exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_exit1ActionPerformed(evt);
            }
        });

        Btn_clear1.setText("Clear");
        Btn_clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_clear1ActionPerformed(evt);
            }
        });

        Btn_enc.setText("Encryption");
        Btn_enc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_encActionPerformed(evt);
            }
        });

        jLabel14.setText("Output Image: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14)
                                .addGap(211, 211, 211))
                            .addComponent(TX_output_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TX_input_key, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_enc)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TX_input_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TX_input_mess, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Btn_input_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Btn_input_mess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(jScrollPane1)))
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(Btn_clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(Btn_exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Btn_input_img)
                            .addComponent(TX_input_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Btn_input_mess)
                            .addComponent(TX_input_mess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TX_input_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TX_output_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_enc))
                        .addGap(8, 8, 8)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_exit1)
                            .addComponent(Btn_clear1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("EnCryption", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Choose Image: ");

        Btn_decryp_img.setText("Browse");
        Btn_decryp_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_decryp_imgActionPerformed(evt);
            }
        });

        jLabel20.setText("Message: ");

        TXA_decryp_mess.setColumns(20);
        TXA_decryp_mess.setRows(5);
        jScrollPane2.setViewportView(TXA_decryp_mess);

        jLabel21.setText("Key : ");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("NOTIFICATION"));

        LB_notify2.setText("notify");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_notify2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_notify2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Image Detail"));

        LB_enc_img2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("Encrypted image");

        LB_enc_img_size2.setText("Size: ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(LB_enc_img2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel25)
                        .addGap(73, 73, 73)
                        .addComponent(LB_enc_img_size2)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_enc_img2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(LB_enc_img_size2))
                .addContainerGap())
        );

        Btn_exit2.setText("Exit");
        Btn_exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_exit2ActionPerformed(evt);
            }
        });

        Btn_decryp.setText("Decryption");
        Btn_decryp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_decrypActionPerformed(evt);
            }
        });

        Btn_clear2.setText("Clear");
        Btn_clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_clear2ActionPerformed(evt);
            }
        });

        Btb_save_mess.setText("Save Message");
        Btb_save_mess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btb_save_messActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TX_decryp_img, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(TX_decryp_key))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Btn_decryp_img)
                                    .addComponent(Btn_decryp))
                                .addGap(11, 11, 11))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Btb_save_mess)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Btn_clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_decryp_img)
                    .addComponent(TX_decryp_img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TX_decryp_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_decryp))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btb_save_mess)
                .addGap(8, 8, 8)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_exit2)
                    .addComponent(Btn_clear2))
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Decryption", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("HỌC VIỆN CÔNG NGHỆ BƯU CHÍNH VIỄN THÔNG TPHCM");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("KHOA CÔNG NGHỆ THÔNG TIN 2");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Đồ án thực tập tốt nghiệp năm 2018");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Đề tài : Nghiên cứu và triển khai kỹ thuật giấu thông tin vào hình ảnh");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Giáo viên hướng dẫn: TS.Huỳnh Trọng Thưa");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Sinh viên thực hiên: Nguyễn Quang Tuấn Lộc");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("MSSV: N14DCAT097");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Lớp: D14CAQT01-N");

        Btn_exit3.setText("Exit");
        Btn_exit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_exit3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1)
                        .addComponent(jLabel3)))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(472, 472, 472))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Btn_exit3))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("About", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_input_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_input_imgActionPerformed
        JFileChooser file = new JFileChooser(".");
        file.setAcceptAllFileFilterUsed(false);
        file.setCurrentDirectory(new File(System.getProperty("user.dir")));
        file.setDialogTitle("Select Image To Encrypt");
        //loc file chi lay dinh dang bmp hoac png
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images (bmp, png)", "bmp", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //neu nguoi dung nhan nut save tren dialog
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            sourceFilePath = path;
            try {
                BufferedImage image = ImageIO.read(selectedFile);
                BufferedImage resizedImage = resize(image, LB_origin_img1.getWidth(), LB_origin_img1.getHeight());
                LB_origin_img1.setIcon(new ImageIcon(resizedImage));
                TX_input_img.setText(path);
                LB_origin_img_size1.setText("Size: " + selectedFile.length() / 1000 + " KB");
            } catch (IOException ex) {
                LB_notify1.setText("<html>"+ex.getMessage()+"<html>");
            }
        } //neu nguoi dung nhan nut cancel tren dialog
        else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_Btn_input_imgActionPerformed

    private void Btn_decryp_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_decryp_imgActionPerformed
        JFileChooser file = new JFileChooser();
        file.setAcceptAllFileFilterUsed(false);
        file.setCurrentDirectory(new File(System.getProperty("user.dir")));
        file.setDialogTitle("Select Image To Decrypt");
        //loc file chi lay dinh dang bmp hoac png
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images (bmp, png)", "bmp", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //neu nguoi dung nhan nut save tren dialog
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            destFilePath = path;
            try {
                BufferedImage image = ImageIO.read(selectedFile);
                BufferedImage resizedImage = resize(image, LB_enc_img2.getWidth(), LB_enc_img2.getHeight());
                LB_enc_img2.setIcon(new ImageIcon(resizedImage));
                TX_decryp_img.setText(path);
                LB_enc_img_size2.setText("Size: " + selectedFile.length() / 1000 + " KB");
            } catch (IOException ex) {
//                showMessage(ex.getMessage(), "ERROR!!!");
                LB_notify2.setText("<html>"+ex.getMessage()+"<html>");
            }
        } //neu nguoi dung nhan nut cancel tren dialog
        else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_Btn_decryp_imgActionPerformed

    private void Btn_input_messActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_input_messActionPerformed
        JFileChooser file = new JFileChooser();
        file.setAcceptAllFileFilterUsed(false);
        file.setCurrentDirectory(new File(System.getProperty("user.dir")));
        file.setDialogTitle("Select Message text To Encrypt");
        //loc file chi lay dinh dang txt
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text (txt)", "txt");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //neu nguoi dung nhan nut save tren dialog
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            try {
                FileReader reader = new FileReader(path);
                BufferedReader br = new BufferedReader(reader);
                TXA_input_mess.read(br, null);
                br.close();
                TXA_input_mess.requestFocus();
                TX_input_mess.setText(path);
            } catch (Exception e2) {
                System.out.println(e2);
            }
        } //neu nguoi dung nhan nut cancel tren dialog
        else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_Btn_input_messActionPerformed

    private void Btn_exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_exit2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_exit2ActionPerformed

    private void Btn_exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_exit1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_exit1ActionPerformed

    private void Btn_clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_clear1ActionPerformed
        TX_input_img.setText("");
        TX_input_mess.setText("");
        TXA_input_mess.setText("");
        TX_input_key.setText("");
        TX_output_img.setText("");
        LB_notify1.setText("");
        LB_origin_img1.setIcon(null);
        LB_enc_img1.setIcon(null);
        LB_origin_img_size1.setText("Size: ");
        LB_enc_img_size1.setText("Size: ");
        sourceFilePath = "";
    }//GEN-LAST:event_Btn_clear1ActionPerformed

    private void Btn_clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_clear2ActionPerformed
        TX_decryp_img.setText("");
        TXA_decryp_mess.setText("");
        TX_decryp_key.setText("");
        LB_notify2.setText("");
        LB_enc_img_size2.setText("Size: ");
        LB_enc_img2.setIcon(null);
        destFilePath = "";
    }//GEN-LAST:event_Btn_clear2ActionPerformed

    private void Btb_save_messActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btb_save_messActionPerformed
        String mess = TXA_decryp_mess.getText();
        JFileChooser file = new JFileChooser();
        file.setAcceptAllFileFilterUsed(false);
        file.setCurrentDirectory(new File(System.getProperty("user.dir")));
        file.setDialogTitle("Select file to save Message text");
        //loc file chi lay dinh dang txt
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Text (txt)", "txt");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        //neu nguoi dung nhan nut save tren dialog
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            if (!path.endsWith(".txt")) {
                try (PrintWriter out = new PrintWriter(path + ".txt")) {
                    out.println(mess);
                    out.close();
                } catch (Exception e2) {
                    System.out.println(e2);
                }
            } else {
                try (PrintWriter out = new PrintWriter(path)) {
                    out.println(mess);
                    out.close();
                } catch (Exception e2) {
                    System.out.println(e2);
                }
            }
        } //neu nguoi dung nhan nut cancel tren dialog
        else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_Btb_save_messActionPerformed

    private void Btn_exit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_exit3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Btn_exit3ActionPerformed

    private void Btn_encActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_encActionPerformed
        if (sourceFilePath.equals("")) {
            LB_notify1.setText("No image file selected");
            return;
        }
        //lay thong diep tù nguoi dung
        String secret = TXA_input_mess.getText().trim();
        if (secret.equals("")) {
            LB_notify1.setText("Please input something to hide");
            return;
        }
        System.out.println("LENG: " + secret.length() * 8 + " bits");
        //xac dinh toi da cac ky tu co the giau tren anh dua vao chiều rộng và chiều cao của hình ảnh
        try {
            BufferedImage bi = ImageIO.read(new File(sourceFilePath));
            int maxChars = getMaxHiddenChars(bi.getWidth(), bi.getHeight());
            if ((secret.length() * 8) > (maxChars) - 3) {
                LB_notify1.setText("The maximum character to hide is " + maxChars);
                return;
            } else {
                LB_notify1.setText("");
            }

        } catch (IOException ioe) {
            LB_notify1.setText("<html>"+ioe.getMessage()+"<html>");
        }
        //chon file save
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Specify a file to save encryted image");
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));

        String ext = sourceFilePath.substring(sourceFilePath.lastIndexOf('.') + 1);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images ", ext);
        fileChooser.addChoosableFileFilter(filter);

        int userSelection = fileChooser.showSaveDialog(this);
        String destFilePath = "";
        //neu nguoi dung nhan nut save tren dialog
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            destFilePath = fileToSave.getAbsolutePath();
            try {
                // encrypt 
//                String secKey = aes.getSecretEncryptionKey();
//                SecretKey originalKey = aes.getSecretDecryptionKey(secKey);
//                byte[] cipherText = aes.encryptText(secret, originalKey);
//                TX_input_key.setText(secKey);
                String key = TX_input_key.getText();
                String newmess = myaes.encrypt(secret, key);
                System.out.println("newmess: "+newmess);
                //encode here
                if (s.Encode(sourceFilePath, newmess, destFilePath)) {
//                if (s.Encode(sourceFilePath, aes.bytesToHex(cipherText), destFilePath)) {
//                if (s.Encode(sourceFilePath, secret, destFilePath)) {
//                    try {
                        File newfile;
                        String fileType = "." + ext;
                        System.out.println("fileType: " + fileType);
                        if (!destFilePath.endsWith(fileType)) {
                            if (destFilePath.indexOf(".") != -1) {
                                destFilePath = destFilePath.substring(0, destFilePath.lastIndexOf('.'));
                            }
                            newfile = new File(destFilePath + fileType);
                            TX_output_img.setText(destFilePath + fileType);
                        } else {
                            newfile = new File(destFilePath);
                            TX_output_img.setText(destFilePath);
                        }
                        // set lai encrypted image 
                        BufferedImage image = ImageIO.read(newfile);
                        BufferedImage resizedImage = resize(image, LB_enc_img1.getWidth(), LB_enc_img1.getHeight());
                        LB_enc_img1.setIcon(new ImageIcon(resizedImage));
                        LB_enc_img_size1.setText("Size: " + newfile.length() / 1000 + " KB");
//                    } catch (IOException ex) {
//                        LB_notify1.setText("<html>"+ex.getMessage()+"<html>");
//                    }
                    LB_notify1.setText("The secret was encoding successfully");
                }
            } catch (Exception ex) {
                LB_notify1.setText("<html>"+ex.getMessage()+"<html>");
            }
        }//neu nguoi dung nhan nut cancel tren dialog
        else if (userSelection == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_Btn_encActionPerformed

    private void Btn_decrypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_decrypActionPerformed
        TXA_decryp_mess.setText("");
        LB_notify2.setText("");
        if (destFilePath.equals("")) {
            LB_notify2.setText("No File Selected");
            return;
        }
//        else if(TX_decryp_key.getText().equals("")){
//            LB_notify2.setText("Please input key");
//        }
        else {
            //decrypt
//            String secKey=TX_decryp_key.getText();
            String secret = s.Decode(destFilePath);
                    System.out.println("sec: "+secret);
//            byte[] decodedHex = aes.hextoBytes(secret);
//            SecretKey originalKey;
//            try {
//                originalKey = aes.getSecretDecryptionKey(secKey);
//                String decryptedText = aes.decryptText(decodedHex, originalKey);
                String key = TX_decryp_key.getText();
                String decryptedText = myaes.decrypt(secret, key);
                TXA_decryp_mess.setText(decryptedText); 
                LB_notify2.setText("The secret was Decoding successfully");
//            } catch (Exception ex) {
//                LB_notify2.setText("<html>"+ex.getMessage()+"<html>");
//            }
        }
//        else {
//            String secret = s.Decode(sourceFilePath);
//            try {
//                TXA_decryp_mess.setText(secret); 
//                LB_notify2.setText("The secret was Decoding successfully");
//            } catch (Exception ex) {
//                LB_notify2.setText("<html>"+ex.getMessage()+"<html>");
//            }
//        }
    }//GEN-LAST:event_Btn_decrypActionPerformed
    public int getMaxHiddenChars(int width, int height) {

        return (width * height * 3); //*3 RGB hide in 1 lsb bit
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btb_save_mess;
    private javax.swing.JButton Btn_clear1;
    private javax.swing.JButton Btn_clear2;
    private javax.swing.JButton Btn_decryp;
    private javax.swing.JButton Btn_decryp_img;
    private javax.swing.JButton Btn_enc;
    private javax.swing.JButton Btn_exit1;
    private javax.swing.JButton Btn_exit2;
    private javax.swing.JButton Btn_exit3;
    private javax.swing.JButton Btn_input_img;
    private javax.swing.JButton Btn_input_mess;
    private javax.swing.JLabel LB_enc_img1;
    private javax.swing.JLabel LB_enc_img2;
    private javax.swing.JLabel LB_enc_img_size1;
    private javax.swing.JLabel LB_enc_img_size2;
    private javax.swing.JLabel LB_notify1;
    private javax.swing.JLabel LB_notify2;
    private javax.swing.JLabel LB_origin_img1;
    private javax.swing.JLabel LB_origin_img_size1;
    private javax.swing.JTextArea TXA_decryp_mess;
    private javax.swing.JTextArea TXA_input_mess;
    private javax.swing.JTextField TX_decryp_img;
    private javax.swing.JTextField TX_decryp_key;
    private javax.swing.JTextField TX_input_img;
    private javax.swing.JTextField TX_input_key;
    private javax.swing.JTextField TX_input_mess;
    private javax.swing.JTextField TX_output_img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
